export const IPC_CHANNELS = {
  sources: {
    list: 'sources:list',
    create: 'sources:create',
    update: 'sources:update',
    reorder: 'sources:reorder',
    delete: 'sources:delete',
    clear: 'sources:clear',
    previewImport: 'sources:preview-import',
    confirmImport: 'sources:confirm-import',
    importFromFile: 'sources:import-from-file',
    exportToFile: 'sources:export-to-file',
    syncSubscription: 'sources:sync-subscription',
  },
  liveSources: {
    list: 'live-sources:list',
    create: 'live-sources:create',
    update: 'live-sources:update',
    reorder: 'live-sources:reorder',
    delete: 'live-sources:delete',
    clear: 'live-sources:clear',
    previewImport: 'live-sources:preview-import',
    confirmImport: 'live-sources:confirm-import',
    importFromFile: 'live-sources:import-from-file',
    exportToFile: 'live-sources:export-to-file',
  },
  home: { get: 'home:get', getHot: 'home:get-hot' },
  recent: { list: 'recent:list', upsert: 'recent:upsert', remove: 'recent:remove' },
  favorites: {
    list: 'favorites:list',
    isFavorite: 'favorites:is-favorite',
    add: 'favorites:add',
    remove: 'favorites:remove',
  },
  vod: {
    search: 'vod:search',
    cancelSearch: 'vod:cancel-search',
    probeMedia: 'vod:probe-media',
    searchEvent: 'vod:search-event',
  },
  live: { loadPlaylist: 'live:load-playlist' },
  media: { getProxyBaseUrl: 'media:get-proxy-base-url', detectStreamType: 'media:detect-stream-type' },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
    testGitHubProxy: 'settings:test-github-proxy',
    initializeAppData: 'settings:initialize-app-data',
    exportAppData: 'settings:export-app-data',
    importAppData: 'settings:import-app-data',
  },
  updates: {
    getCurrentVersion: 'updates:get-current-version',
    check: 'updates:check',
    download: 'updates:download',
    install: 'updates:install',
    event: 'updates:event',
  },
  window: { isMaximized: 'window:is-maximized', toggleMaximize: 'window:toggle-maximize' },
  shell: { openExternal: 'shell:open-external' },
} as const
