// main 注册器与 preload 调用方共用的唯一 channel 来源，避免字符串漂移。
export const IPC_CHANNELS = {
  sources: {
    list: 'sources:list',
    create: 'sources:create',
    update: 'sources:update',
    switchBackup: 'sources:switch-backup',
    testSpeed: 'sources:test-speed',
    reorder: 'sources:reorder',
    delete: 'sources:delete',
    clear: 'sources:clear',
    previewImport: 'sources:preview-import',
    confirmImport: 'sources:confirm-import',
    importFromFile: 'sources:import-from-file',
    exportToFile: 'sources:export-to-file',
    syncSubscription: 'sources:sync-subscription',
    deleteSubscription: 'sources:delete-subscription',
  },
  iptvSources: {
    list: 'iptv-sources:list',
    create: 'iptv-sources:create',
    update: 'iptv-sources:update',
    reorder: 'iptv-sources:reorder',
    delete: 'iptv-sources:delete',
    clear: 'iptv-sources:clear',
    previewImport: 'iptv-sources:preview-import',
    confirmImport: 'iptv-sources:confirm-import',
    importFromFile: 'iptv-sources:import-from-file',
    exportToFile: 'iptv-sources:export-to-file',
  },
  home: { get: 'home:get', getHot: 'home:get-hot' },
  recent: { list: 'recent:list', upsert: 'recent:upsert', remove: 'recent:remove' },
  favorites: {
    list: 'favorites:list',
    isFavorite: 'favorites:is-favorite',
    add: 'favorites:add',
    remove: 'favorites:remove',
  },
  vod: {
    search: 'vod:search',
    cancelSearch: 'vod:cancel-search',
    getCatalogPage: 'vod:get-catalog-page',
    getDetail: 'vod:get-detail',
    probeMedia: 'vod:probe-media',
    searchEvent: 'vod:search-event',
  },
  iptv: {
    getCatalog: 'iptv:get-catalog',
    getPrograms: 'iptv:get-programs',
    getProgramSchedule: 'iptv:get-program-schedule',
    getPlaybackTarget: 'iptv:get-playback-target',
    testEpg: 'iptv:test-epg',
  },
  radio: {
    getCategories: 'radio:get-categories',
    getCategoryChannels: 'radio:get-category-channels',
    getChannelDetail: 'radio:get-channel-detail',
    searchChannels: 'radio:search-channels',
    getLivePrograms: 'radio:get-live-programs',
    getRegions: 'radio:get-regions',
    getBillboard: 'radio:get-billboard',
    getPlaybackUrl: 'radio:get-playback-url',
  },
  media: {
    getPlaybackTarget: 'media:get-playback-target',
    getAssociatedAudioUrl: 'media:get-associated-audio-url',
    getImageUrl: 'media:get-image-url',
    getPlaybackSessionInfo: 'media:get-playback-session-info',
    retainPlaybackSession: 'media:retain-playback-session',
    releasePlaybackSession: 'media:release-playback-session',
    reportPlaybackEvent: 'media:report-playback-event',
  },
  settings: {
    get: 'settings:get',
    update: 'settings:update',
    restoreFactorySettings: 'settings:restore-factory-settings',
    clearAppData: 'settings:clear-app-data',
    exportAppData: 'settings:export-app-data',
    importAppData: 'settings:import-app-data',
  },
  network: {
    getStatus: 'network:get-status',
    save: 'network:save',
    test: 'network:test',
  },
  updates: {
    getCurrentVersion: 'updates:get-current-version',
    check: 'updates:check',
    download: 'updates:download',
    install: 'updates:install',
    event: 'updates:event',
  },
  window: {
    isMaximized: 'window:is-maximized',
    toggleMaximize: 'window:toggle-maximize',
    quitApp: 'window:quit-app',
    restartApp: 'window:restart-app',
    enterMiniWindowMode: 'window:enter-mini-window-mode',
    getMiniWindowPlayback: 'window:get-mini-window-playback',
    updateMiniWindowPlayback: 'window:update-mini-window-playback',
    resizeMiniWindow: 'window:resize-mini-window',
    moveMiniWindow: 'window:move-mini-window',
    hideMiniWindow: 'window:hide-mini-window',
    getMiniWindowAlwaysOnTop: 'window:get-mini-window-always-on-top',
    setMiniWindowAlwaysOnTop: 'window:set-mini-window-always-on-top',
    exitMiniWindowMode: 'window:exit-mini-window-mode',
    miniWindowModeExit: 'window:mini-window-mode-exit',
  },
  shell: { openExternal: 'shell:open-external' },
} as const
