export const APP_DISPLAY_NAME = 'VfanTV'
export const APP_ID = 'com.vfantv.app'
export const USER_DATA_DIR_NAME = 'vfantv'
export const DB_FILE_NAME = 'vfantv.sqlite'
export const DEFAULT_SOURCES_EXPORT_NAME = 'VfanTV-sources.json'
export const DEFAULT_LIVE_SOURCES_EXPORT_NAME = 'VfanTV-live-sources.json'
export const DEFAULT_APP_DATA_EXPORT_NAME = 'VfanTV-data.json'
