export const THEME_STORAGE_KEY = 'vfan-tv-theme'
export const SEARCH_HISTORY_STORAGE_KEY = 'vfan-tv:search-histories'
export const SEARCH_VIEW_MODE_STORAGE_KEY = 'vfan-tv:search-view-mode'
export const SEARCH_CONTEXT_STORAGE_KEY = 'vfan-tv:search-context'
export const SIDEBAR_COLLAPSED_STORAGE_KEY = 'vfan-tv-sidebar-collapsed'
